version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/code
hooks:

  BeforeInstall:
    - location: appspec-scripts/before.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: appspec-scripts/start.sh
      timeout: 300
      runas: root


